apiVersion: v2
name: jobnik
description: Umbrella chart for the Jobnik product
type: application
version: 0.3.0
dependencies:
  - name: jobnik-manager
    version: 0.3.0
    repository: file://../apps/jobnik-manager/helm
    condition: jobnik-manager.enabled
